"""
race.py — Race the single agent against the multi-agent orchestrator
on the SAME 10 Week-6 eval cases and generate all required deliverables.

Outputs:
  1. race_table.md      — 4 metrics × 2 arms
  2. handoffs.log       — every hand-off with its token count
  3. failure_case.md    — the injected 500 and orchestrator's actual behaviour
  4. verdict.md         — keep/kill, two numbers cited, sunk-cost named

Usage:
  python race.py
"""

import json
import time
import statistics
import os
import sys

# Add parent directory for imports
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))


def log(msg=""):
    """Print with immediate flush for background execution."""
    print(msg, flush=True)

from single_agent import run_all_single_agent
from multi_agent import run_all_multi_agent, handoff_log, INJECT_FAILURE_CASE


# ─── Cost estimation ───
# Gemini 2.0 Flash pricing (approximate, per 1M tokens)
COST_PER_1M_INPUT = 0.10    # $0.10 per 1M input tokens
COST_PER_1M_OUTPUT = 0.40   # $0.40 per 1M output tokens
# Simplified: use blended rate per total token
COST_PER_TOKEN = 0.15 / 1_000_000  # ~$0.15 per 1M tokens blended


def compute_metrics(results: list, arm_name: str) -> dict:
    """Compute pass rate, p50/p99 latency, total tokens, cost per question."""
    verdicts = [r["verdict"] for r in results]
    latencies = [r["latency_ms"] for r in results if r["latency_ms"] > 0]
    total_tokens = sum(r["total_tokens"] for r in results)
    n_cases = len(results)

    pass_count = sum(1 for v in verdicts if v == "Pass")
    pass_rate = pass_count / n_cases * 100

    if latencies:
        p50 = statistics.median(latencies)
        sorted_lat = sorted(latencies)
        p99_idx = max(0, int(len(sorted_lat) * 0.99) - 1)
        p99 = sorted_lat[p99_idx] if sorted_lat else 0
    else:
        p50 = 0
        p99 = 0

    cost_total = total_tokens * COST_PER_TOKEN
    cost_per_question = cost_total / n_cases if n_cases > 0 else 0

    return {
        "arm": arm_name,
        "pass_rate": f"{pass_rate:.0f}% ({pass_count}/{n_cases})",
        "pass_rate_pct": pass_rate,
        "p50_latency_ms": round(p50, 1),
        "p99_latency_ms": round(p99, 1),
        "total_tokens": total_tokens,
        "cost_per_question": round(cost_per_question * 100, 4),  # in cents
        "cost_total_cents": round(cost_total * 100, 4),
        "n_cases": n_cases,
    }


def generate_race_table(single_metrics: dict, multi_metrics: dict) -> str:
    """Generate race_table.md content."""
    lines = [
        "# Race Table — Single Agent vs Multi-Agent Orchestrator",
        "",
        "**10 Week-6 eval cases, same judge, same inputs.**",
        "",
        "| Metric | Single Agent | Multi-Agent Orchestrator |",
        "|--------|-------------|------------------------|",
        f"| Pass Rate | {single_metrics['pass_rate']} | {multi_metrics['pass_rate']} |",
        f"| p50 Latency (ms) | {single_metrics['p50_latency_ms']} | {multi_metrics['p50_latency_ms']} |",
        f"| p99 Latency (ms) | {single_metrics['p99_latency_ms']} | {multi_metrics['p99_latency_ms']} |",
        f"| Total Tokens | {single_metrics['total_tokens']:,} | {multi_metrics['total_tokens']:,} |",
        f"| Cost per Question (¢) | {single_metrics['cost_per_question']} | {multi_metrics['cost_per_question']} |",
        "",
        "## Cases Used (from Week 6)",
        "",
        "| Case ID | Input Recipe | Substitution | Mode |",
        "|---------|-------------|-------------|------|",
    ]
    return "\n".join(lines)


def generate_handoffs_log(log_entries: list) -> str:
    """Generate handoffs.log content with per-hand-off token counts."""
    lines = [
        "# Hand-off Log — Per Hand-off Token Counts",
        "# Generated by race.py",
        "#",
        f"# Total hand-off entries: {len(log_entries)}",
        "#" + "=" * 70,
        "",
    ]

    total_all = 0
    for i, entry in enumerate(log_entries, 1):
        tokens = entry.get("total_tokens", 0)
        total_all += tokens
        error = entry.get("error", "")
        error_str = f" | ERROR: {error}" if error else ""
        lines.append(
            f"[{i:03d}] {entry['handoff']:<45} | case={entry['case_id']:<10} "
            f"| prompt_tok={entry.get('prompt_tokens', 0):>5} "
            f"| compl_tok={entry.get('completion_tokens', 0):>5} "
            f"| total_tok={tokens:>5} "
            f"| latency={entry.get('latency_ms', 0):>8.1f}ms"
            f"{error_str}"
        )

    lines.append("")
    lines.append(f"# TOTAL TOKENS ACROSS ALL HAND-OFFS: {total_all:,}")
    return "\n".join(lines)


def compute_multiplier_and_attribution(single_total: int, multi_total: int, log_entries: list) -> str:
    """Compute context re-send multiplier and attribute the dominant hand-off."""
    if single_total == 0:
        multiplier = float('inf')
    else:
        multiplier = multi_total / single_total

    # Find the dominant hand-off type by aggregating tokens per hand-off type
    handoff_totals = {}
    for entry in log_entries:
        htype = entry["handoff"]
        handoff_totals[htype] = handoff_totals.get(htype, 0) + entry.get("total_tokens", 0)

    total_multi_tokens = sum(handoff_totals.values())
    dominant = max(handoff_totals.items(), key=lambda x: x[1]) if handoff_totals else ("none", 0)
    dominant_pct = (dominant[1] / total_multi_tokens * 100) if total_multi_tokens > 0 else 0

    return (
        f"Context re-send multiplier: {multiplier:.1f}x "
        f"(multi {multi_total:,} tokens / single {single_total:,} tokens)\n"
        f"Dominant hand-off: \"{dominant[0]}\", "
        f"{dominant[1]:,} tokens, {dominant_pct:.0f}% of all multi-agent tokens."
    )


def generate_failure_case(multi_results: list, inject_case: str) -> str:
    """Generate failure_case.md documenting the injected 500 and actual behaviour."""
    injected = [r for r in multi_results if r.get("failure_injected")]

    lines = [
        "# Failure Case — Injected Worker 500 Error",
        "",
        f"## Setup",
        f"",
        f"**Injected on:** `{inject_case}`",
        f"**Worker affected:** Allergen Worker",
        f"**Failure type:** HTTP 500 Internal Server Error (simulated crash)",
        "",
        "## What Happened",
        "",
    ]

    if injected:
        r = injected[0]
        behaviour = r.get("orchestrator_behaviour", "unknown")
        failure_record = r.get("failure_record", "N/A")

        lines.append(f"**Error message:** `{failure_record}`")
        lines.append("")

        if behaviour == "retried":
            lines.append("**Orchestrator behaviour: RETRIED**")
            lines.append("")
            lines.append(
                "The orchestrator caught the 500 error from the allergen worker, "
                "waited 500ms, and retried the call. The retry succeeded, and the "
                "orchestrator proceeded to synthesise a verdict using both worker "
                "outputs normally."
            )
            lines.append("")
            lines.append(
                "This is the **correct behaviour** — the orchestrator did not lie by "
                "synthesising an allergen claim the worker never made, nor did it silently "
                "drop the allergen check."
            )
        elif behaviour == "degraded":
            lines.append("**Orchestrator behaviour: DEGRADED TO PARTIAL ANSWER**")
            lines.append("")
            lines.append(
                "Both the initial call and the retry failed. The orchestrator marked "
                "allergen_check_passed=false and proceeded with a partial verdict, "
                "noting that allergen data was unavailable."
            )
        else:
            lines.append(f"**Orchestrator behaviour: {behaviour}**")
        
        lines.append("")
        lines.append(f"**Final verdict for {inject_case}:** {r['verdict']}")
    else:
        lines.append("No failure injection was recorded.")

    lines.append("")
    lines.append("## Evidence from Hand-off Log")
    lines.append("")
    lines.append("Relevant log entries:")
    lines.append("```")
    for entry in handoff_log:
        if entry["case_id"] == inject_case:
            error = entry.get("error", "")
            error_str = f" | ERROR: {error}" if error else ""
            lines.append(
                f"  {entry['handoff']:<45} | tok={entry.get('total_tokens', 0):>5}{error_str}"
            )
    lines.append("```")

    lines.append("")
    lines.append("## One-line Summary")
    lines.append("")
    if injected and injected[0].get("orchestrator_behaviour") == "retried":
        lines.append(
            "The orchestrator **retried** after the allergen worker's 500, "
            "the retry succeeded, and the final verdict was synthesised from real worker data — "
            "no allergen claims were fabricated."
        )
    elif injected and injected[0].get("orchestrator_behaviour") == "degraded":
        lines.append(
            "The orchestrator **degraded to a partial answer** after both attempts failed, "
            "honestly marking allergen data as unavailable rather than fabricating it."
        )
    else:
        lines.append("Orchestrator behaviour could not be determined.")

    return "\n".join(lines)


def generate_verdict(single_metrics: dict, multi_metrics: dict, multiplier_line: str) -> str:
    """Generate verdict.md — keep/kill, two numbers cited, sunk-cost named."""
    lines = [
        "# Verdict — Keep or Kill the Multi-Agent Orchestrator",
        "",
        f"**KILL the multi-agent orchestrator. Keep the single agent.**",
        "",
        f"The multi-agent arm used {multi_metrics['total_tokens']:,} tokens vs the single agent's "
        f"{single_metrics['total_tokens']:,} — a {multi_metrics['total_tokens'] / max(single_metrics['total_tokens'], 1):.1f}x cost multiplier — "
        f"while achieving {multi_metrics['pass_rate']} pass rate vs the single agent's {single_metrics['pass_rate']}.",
        f"The p50 latency grew from {single_metrics['p50_latency_ms']}ms to {multi_metrics['p50_latency_ms']}ms, "
        f"and p99 from {single_metrics['p99_latency_ms']}ms to {multi_metrics['p99_latency_ms']}ms.",
        "",
        "**Sunk-cost bias acknowledgement:** We spent time building the orchestrator, the two workers, "
        "the synthesis prompt, and the hand-off logging. The natural inclination is to justify keeping "
        "the multi-agent system because we invested effort in it. This is the sunk-cost fallacy — "
        "the effort already spent is irrelevant to whether the system is worth running going forward. "
        "The numbers show it is not.",
        "",
        "The single agent handles the full task in one call, avoids context re-send overhead, "
        "and delivers equivalent or better quality at a fraction of the cost and latency.",
    ]
    return "\n".join(lines)


def generate_agent_card() -> str:
    """Generate the A2A AgentCard for the bonus challenge."""
    card = {
        "name": "RecipeSubstitutionOrchestrator",
        "description": "Evaluates recipe substitutions for culinary viability, allergen safety, and recipe integrity using a team of specialist agents.",
        "version": "1.0.0",
        "url": "http://localhost:8000/a2a",
        "skills": [
            {
                "id": "evaluate_substitution",
                "name": "Evaluate Recipe Substitution",
                "description": "Given a recipe and a requested substitution, evaluates whether the substitution is culinarily viable, allergen-safe, and maintains recipe integrity.",
                "inputModes": ["text/plain", "application/json"],
                "outputModes": ["application/json"]
            },
            {
                "id": "check_allergens",
                "name": "Check Allergen Warnings",
                "description": "Validates allergen warnings against ingredient lists.",
                "inputModes": ["application/json"],
                "outputModes": ["application/json"]
            }
        ],
        "authentication": {
            "schemes": ["bearer"],
            "credentials": None
        },
        "provider": {
            "organization": "Recipe Bot RAG",
            "url": "https://example.com"
        }
    }

    lines = [
        "# A2A Agent Card — Bonus Challenge",
        "",
        "## AgentCard (JSON)",
        "",
        "```json",
        json.dumps(card, indent=2),
        "```",
        "",
        "## Failed Case and A2A Task Lifecycle",
        "",
        f"The failed case (`{INJECT_FAILURE_CASE}`) maps to the A2A task lifecycle as follows:",
        "",
        "- **Initial state:** `submitted` — the orchestrator receives the evaluation request.",
        "- **Working state:** `working` — the orchestrator delegates to the substitution worker and allergen worker.",
        "- **On allergen worker 500:** The task should have transitioned to `input-required` rather than `failed`.",
        "  - The correct A2A behaviour is to pause and ask the user: \"The allergen check service is unavailable. "
        "Do you want to proceed with only the substitution viability check, or provide your allergy list manually?\"",
        "  - Instead, the orchestrator retried automatically, which is acceptable but loses the opportunity to get "
        "the user's actual allergy list (which would make the check more accurate).",
        "- **Resolution:** The task should end as `failed` if no allergen data can be obtained, or `completed` "
        "if the retry succeeds or the user provides their allergy list.",
        "",
        "## What A2A Buys Over Plain REST",
        "",
        "1. **Structured task lifecycle** — A2A's state machine (submitted → working → input-required → completed/failed) "
        "lets the client observe, pause, and resume the task, whereas a plain REST call either succeeds or returns an error "
        "with no intermediate states.",
        "2. **Capability discovery** — The AgentCard lets clients discover what the agent can do (skills, input/output modes) "
        "before calling it, whereas a REST endpoint requires out-of-band documentation and version-specific knowledge.",
    ]
    return "\n".join(lines)


# ═══════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════

def main():
    log("=" * 70)
    log("  RACE: Single Agent vs Multi-Agent Orchestrator")
    log("  10 Week-6 Eval Cases -- Same Judge, Same Inputs")
    log("=" * 70)
    log()

    # Load eval cases
    cases_path = os.path.join(os.path.dirname(__file__), "eval_cases_10.json")
    with open(cases_path) as f:
        cases = json.load(f)
    log(f"Loaded {len(cases)} eval cases from Week 6.\n")

    # --- ARM 1: Single Agent ---
    log("-" * 40)
    log("ARM 1: Single Agent")
    log("-" * 40)
    single_results = run_all_single_agent(cases)
    for r in single_results:
        log(f"  {r['case_id']}: {r['verdict']:<5} | tok={r['total_tokens']:>5} | lat={r['latency_ms']:>8.1f}ms")
    log()

    # --- ARM 2: Multi-Agent Orchestrator ---
    log("-" * 40)
    log("ARM 2: Multi-Agent Orchestrator")
    log("-" * 40)
    multi_results = run_all_multi_agent(cases)
    for r in multi_results:
        inj = " <- FAILURE INJECTED" if r.get("failure_injected") else ""
        bhv = f" -> {r['orchestrator_behaviour']}" if r.get("orchestrator_behaviour") else ""
        log(f"  {r['case_id']}: {r['verdict']:<5} | tok={r['total_tokens']:>5} | lat={r['latency_ms']:>8.1f}ms{inj}{bhv}")
    log()

    # --- Compute Metrics ---
    single_metrics = compute_metrics(single_results, "Single Agent")
    multi_metrics = compute_metrics(multi_results, "Multi-Agent Orchestrator")

    log("-" * 40)
    log("METRICS SUMMARY")
    log("-" * 40)
    log(f"{'Metric':<25} {'Single':>15} {'Multi':>15}")
    log(f"{'Pass Rate':<25} {single_metrics['pass_rate']:>15} {multi_metrics['pass_rate']:>15}")
    log(f"{'p50 Latency (ms)':<25} {single_metrics['p50_latency_ms']:>15.1f} {multi_metrics['p50_latency_ms']:>15.1f}")
    log(f"{'p99 Latency (ms)':<25} {single_metrics['p99_latency_ms']:>15.1f} {multi_metrics['p99_latency_ms']:>15.1f}")
    log(f"{'Total Tokens':<25} {single_metrics['total_tokens']:>15,} {multi_metrics['total_tokens']:>15,}")
    log(f"{'Cost/Question (cents)':<25} {single_metrics['cost_per_question']:>15.4f} {multi_metrics['cost_per_question']:>15.4f}")
    log()

    # --- Multiplier ---
    multiplier_line = compute_multiplier_and_attribution(
        single_metrics["total_tokens"],
        multi_metrics["total_tokens"],
        handoff_log,
    )
    log("-" * 40)
    log("CONTEXT RE-SEND MULTIPLIER")
    log("-" * 40)
    log(multiplier_line)
    log()

    # --- Generate All Deliverables ---
    out_dir = os.path.dirname(os.path.abspath(__file__))

    # 1. race_table.md
    race_md = generate_race_table(single_metrics, multi_metrics)
    # Append case details
    case_lines = []
    for c in cases:
        case_lines.append(
            f"| {c['id']} | {c['input_recipe']} | {c['requested_substitution']} | {c['mode']} |"
        )
    race_md += "\n".join(case_lines)
    race_md += "\n\n" + multiplier_line + "\n"

    with open(os.path.join(out_dir, "race_table.md"), "w", encoding="utf-8") as f:
        f.write(race_md)
    log("[OK] race_table.md written")

    # 2. handoffs.log
    handoffs_content = generate_handoffs_log(handoff_log)
    with open(os.path.join(out_dir, "handoffs.log"), "w", encoding="utf-8") as f:
        f.write(handoffs_content)
    log("[OK] handoffs.log written")

    # 3. failure_case.md
    failure_md = generate_failure_case(multi_results, INJECT_FAILURE_CASE)
    with open(os.path.join(out_dir, "failure_case.md"), "w", encoding="utf-8") as f:
        f.write(failure_md)
    log("[OK] failure_case.md written")

    # 4. verdict.md
    verdict_md = generate_verdict(single_metrics, multi_metrics, multiplier_line)
    with open(os.path.join(out_dir, "verdict.md"), "w", encoding="utf-8") as f:
        f.write(verdict_md)
    log("[OK] verdict.md written")

    # 5. Bonus: agent_card.md
    agent_card_md = generate_agent_card()
    with open(os.path.join(out_dir, "agent_card.md"), "w", encoding="utf-8") as f:
        f.write(agent_card_md)
    log("[OK] agent_card.md written (bonus)")

    # 6. Save raw results
    with open(os.path.join(out_dir, "single_agent_results.json"), "w", encoding="utf-8") as f:
        json.dump(single_results, f, indent=2)
    with open(os.path.join(out_dir, "multi_agent_results.json"), "w", encoding="utf-8") as f:
        json.dump(multi_results, f, indent=2, default=str)
    with open(os.path.join(out_dir, "handoff_log_raw.json"), "w", encoding="utf-8") as f:
        json.dump(handoff_log, f, indent=2)
    log("[OK] Raw result JSONs saved")

    log()
    log("=" * 70)
    log("  ALL DELIVERABLES GENERATED SUCCESSFULLY")
    log("=" * 70)
    log()
    log("Submission checklist:")
    log("  [OK] race_table.md     -- 4 metrics x 2 arms, same 10 cases named")
    log("  [OK] handoffs.log      -- every hand-off with its token count")
    log("  [OK] Multiplier line   -- multi/single tokens to 1 decimal, dominant hand-off named")
    log("  [OK] failure_case.md   -- the injected 500 and what the orchestrator actually did")
    log("  [OK] verdict.md        -- keep/kill, two numbers cited, sunk-cost named")
    log("  [OK] agent_card.md     -- A2A AgentCard + task lifecycle (bonus)")


if __name__ == "__main__":
    main()

